name: homework_2_deployment

on: workflow_dispatch

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: |
          cd ./homework_2_type_annotations
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Check with mypy
        run: |
          cd ./homework_2_type_annotations
          poetry run mypy
